[workspace]
members = [
    "programs/*",
    "tip-payment-cli",
    "tip-distribution-cli",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false

[workspace.dependencies]
anchor-lang = "0.31.1"
proc-macro2 = "1.0.95"

