[package]
name = "jito-tip-distribution-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { workspace = true }
jito-tip-distribution = { features = ["no-entrypoint", "no-idl"], path = "../tip-distribution" }
proc-macro2 = { workspace = true }
